inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true
  Exclude:
    - spec/**/*

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
  Max: 30

MethodLength:
  Max: 20

Layout/EmptyLineAfterGuardClause:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 8
