sudo: false
language: ruby
rvm: 2.3.1
cache:
  bundler: true

before_script:
  - bundle exec rake db:create db:setup RAILS_ENV=test

script:
  - bundle exec rake spec
  - bundle exec rubocop -R
  - gem install bundler-audit brakeman
  - bundle audit check --update
  - brakeman -A -z --ensure-latest