development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

staging:
  adapter: redis
  url: <%= "redis://#{ENV.fetch('REDIS_PORT_6379_TCP_ADDR')}:#{ENV.fetch('REDIS_PORT_6379_TCP_PORT')}/6" %>
  channel_prefix: mobile_content_api_staging_channel

production:
  adapter: redis
  url: <%= "redis://#{ENV.fetch('REDIS_PORT_6379_TCP_ADDR')}:#{ENV.fetch('REDIS_PORT_6379_TCP_PORT')}/6" %>
  channel_prefix: mobile_content_api_production_channel
