development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

staging:
  adapter: redis
  url: <%= "redis://#{ENV.fetch('STORAGE_REDIS_HOST')}:#{ENV.fetch('STORAGE_REDIS_PORT')}/#{ENV.fetch('STORAGE_REDIS_DB_INDEX')}" %>
  channel_prefix: mobile_content_api_staging_channel

production:
  adapter: redis
  url: <%= "redis://#{ENV.fetch('STORAGE_REDIS_HOST')}:#{ENV.fetch('STORAGE_REDIS_PORT')}/#{ENV.fetch('STORAGE_REDIS_DB_INDEX')}" %>
  channel_prefix: mobile_content_api_production_channel
